export const supportedLocales = ["en", "zh-CN", "ko", "ja"] as const;
export type Locale = typeof supportedLocales[number];

export const localeNames: Record<Locale, string> = { en: "English", "zh-CN": "中文", ko: "한국어", ja: "日本語" };

const dictionaries: Record<Exclude<Locale, "en">, Record<string, string>> = {
  "zh-CN": {
    "Search workspace": "搜索工作区", "Quick links": "快捷链接", "Canvas": "画布", "Campaigns": "营销活动", "Segments": "细分", "Getting Started": "入门", "Performance Overview": "效果概览", "Agent Console": "智能体控制台", "Messaging": "消息", "Audience": "受众", "Content": "内容", "Analytics": "分析", "Partner Integrations": "合作伙伴集成", "Data Settings": "数据设置", "Settings": "设置", "Catalogs": "目录", "Language": "语言",
    "Feature Flags": "功能开关", "Landing Pages": "落地页", "Surveys": "问卷", "Banners": "横幅", "Content Calendar": "内容日历", "Messaging Diagnostics": "消息诊断", "Segment Extensions": "细分扩展", "Global Control Group": "全局控制组", "Suppression Lists": "抑制列表", "Manage Audience": "管理受众", "Import Users": "导入用户", "Locations": "位置", "Media Library": "媒体库", "Banner Templates": "横幅模板", "Canvas Templates": "画布模板", "Content Blocks": "内容块", "Email Link Templates": "邮件链接模板", "Email Templates": "邮件模板", "In-App Message Templates": "应用内消息模板", "Webhook Templates": "Webhook 模板", "Promotion Codes": "促销码", "Brand Guidelines": "品牌规范", "Report Builder": "报表生成器", "Custom Events Report": "自定义事件报表", "Global Control Group Report": "全局控制组报表", "Query Builder": "查询生成器", "Engagement Reports": "互动报表", "Revenue Report": "收入报表", "Segment Insights": "细分洞察", "Dashboard Builder": "仪表板生成器", "Email Performance": "邮件效果", "Push Performance": "推送效果", "SMS/MMS/RCS Performance": "短信/MMS/RCS 效果", "Conversions": "转化", "Technology Partners": "技术合作伙伴", "Currents": "Currents", "Data Sharing": "数据共享", "Solutions Partners": "解决方案合作伙伴", "Custom Attributes": "自定义属性", "Custom Events": "自定义事件", "Products": "产品", "Cloud Data Ingestion": "云数据导入", "Data Transformation": "数据转换", "App Settings": "应用设置", "APIs and Identifiers": "API 与标识符", "Event User Log": "事件用户日志", "Internal Groups": "内部组", "Exports Log": "导出日志", "Tag Management": "标签管理", "Email Preferences": "邮件偏好", "Frequency Capping Rules": "频次上限规则", "Push Settings": "推送设置", "Approval Workflow": "审批工作流", "Localization Settings": "本地化设置", "Banner Placements": "横幅位置", "Messaging Rate Limits": "消息速率限制", "Billing": "账单", "User Management": "用户管理", "Canvas Step Agents": "画布步骤智能体", "Data Agents": "数据智能体", "Catalog Agents": "目录智能体",
    "View upcoming scheduled campaigns and related analytics": "查看即将发送的营销活动及相关分析", "Troubleshoot why messages did not send": "排查消息未发送的原因", "Split your audience into targeted groups": "将受众划分为目标群组", "Manage non-user data such as products": "管理产品等非用户数据", "Build and save performance reports": "构建并保存效果报表", "Manage sending and subscription settings": "管理发送和订阅设置", "Manage this area for this workspace": "管理此工作区中的相关功能",
    "Define users, subscriptions, eligibility, and audience controls used by local campaign execution.": "定义本地营销活动执行所需的用户、订阅、资格和受众控制。", "Manage reusable message content, templates, media, catalogs, and promotion data.": "管理可复用的消息内容、模板、媒体、目录和促销数据。", "Configure local representations of partner connections, data sharing, and delivery logs.": "配置合作伙伴连接、数据共享和投递日志的本地模拟。", "Define the data schema and ingestion inputs that power targeting and personalization.": "定义用于目标筛选和个性化的数据结构与导入来源。", "Configure workspace defaults, governance, channel settings, and local access controls.": "配置工作区默认值、治理规则、渠道设置和本地访问控制。", "Configure message assets, entry rules, and delivery diagnostics.": "配置消息素材、进入规则和投递诊断。",
    "Segment builder": "细分生成器", "Custom attribute": "自定义属性", "Local users available for estimates": "可用于估算的本地用户", "Estimate audience": "估算受众", "Segment condition saved to the local workspace.": "细分条件已保存到本地工作区。", "Catalog schema": "目录结构", "Reusable content": "可复用内容", "sku, name, price, image, inventory and custom product fields are available to local Liquid previews.": "本地 Liquid 预览可使用 sku、name、price、image、inventory 和自定义产品字段。", "Resources created here can be selected by the matching campaign composer.": "此处创建的资源可在对应的营销活动编辑器中选择。", "Open related workspace": "打开相关工作区", "Connection status": "连接状态", "Local simulation is enabled. Connection tests render a deterministic success or failure result and do not call external systems.": "本地模拟已启用。连接测试会返回确定的成功或失败结果，不会调用外部系统。", "Test connection": "测试连接", "Local connection test succeeded. No external request was sent.": "本地连接测试成功，未发送外部请求。", "Data definition": "数据定义", "Workspace default": "工作区默认值", "Use workspace default": "使用工作区默认值", "Apply this setting to new local resources and campaigns.": "将此设置应用到新建的本地资源和营销活动。", "Workspace configuration": "工作区配置", "Owner": "负责人", "Draft": "草稿", "Save configuration": "保存配置", "Messaging configuration saved.": "消息配置已保存。",
    "8 days left in your free trial.": "免费试用期还剩 8 天。", "Connect with sales": "联系销售", "Limited access": "受限访问", "Send feedback": "发送反馈", "Take a tour": "查看导览", "Close navigation": "关闭导航", "View by channel": "按渠道查看",
    "Users with the 'Edit Global Control Group' permission can edit, enable, and disable the Global Control Group.": "拥有“编辑全局控制组”权限的用户可以编辑、启用和禁用全局控制组。", "Global Control Group Settings": "全局控制组设置", "Audience settings": "受众设置", "Specify the percentage of users to randomly assign to the Global Control Group.": "指定随机分配到全局控制组的用户百分比。", "Global Control Group percentage": "全局控制组百分比", "of all users to the Global Control Group": "所有用户加入全局控制组", "All users": "所有用户", "Treatment group": "治疗组", "Treatment sample": "治疗组样本", "Audience counts are estimates.": "受众人数为估算值。", "Exclusion settings": "排除设置", "Users in the Global Control Group will be eligible to receive messages from campaigns and Canvases with any specific tags added here.": "全局控制组的用户将有资格接收来自营销活动和画布的消息，这些消息带有此处添加的任何特定标签。", "Add tags": "添加标签", "Update exclusions": "更新例外情况",
    "Campaigns let you send a single, targeted message through email, push, SMS, and more, ensuring timely communication with your audience": "营销活动可通过邮件、推送、短信等渠道向目标受众发送单次消息，及时触达用户", "Create campaign": "创建营销活动", "What kind of campaign would you like to create?": "你想创建哪种营销活动？", "Create with Operator": "使用 Operator 创建", "Generate a coordinated campaign draft": "生成协调一致的营销活动草稿", "MESSAGE ONE OR MORE CHANNELS": "向一个或多个渠道发送消息", "SINGLE CHANNEL": "单一渠道", "TRACK MESSAGES SENT VIA API": "跟踪通过 API 发送的消息", "FEATURE FLAGS": "功能开关", "Multichannel": "多渠道", "Coordinate messages across channels": "跨渠道协调消息", "Email": "电子邮件", "Push notification": "推送通知", "In-app message": "应用内消息", "Feature flag experiment": "功能开关实验", "API campaign": "API 营销活动",
    "All campaigns": "所有营销活动", "All": "全部", "Campaign": "营销活动", "Campaign type": "营销活动类型", "Channel": "渠道", "Tag": "标签", "Entry schedule": "进入计划", "Last edited": "上次编辑", "Actions": "操作", "Columns": "列", "Filters": "筛选", "Active": "启用", "Stopped": "已停止", "Select...": "选择…", "One time": "一次性", "Action-based": "基于操作", "API-triggered": "API 触发", "Duplicate": "复制", "Archive": "归档", "Edit": "编辑", "Export": "导出", "Save Draft": "保存草稿", "Launch Campaign": "启动营销活动", "Campaign Active": "营销活动已启用", "Close editor": "关闭编辑器", "Campaign steps": "营销活动步骤", "Compose Messages": "撰写消息", "Schedule Delivery": "安排投递", "Target Audiences": "目标受众", "Assign Conversions": "分配转化", "Review Summary": "审核摘要", "Compose": "撰写", "Schedule": "计划", "Target": "目标", "Assign": "分配", "Review": "审核", "Forward": "前进", "Back": "返回", "Next": "下一步", "Previous": "上一步", "Save": "保存", "Create": "创建", "Stop": "停止", "Run": "运行",
    "Campaign Details": "营销活动详情", "Campaign Name": "营销活动名称", "Enter Campaign Name": "输入营销活动名称", "Enter a description": "输入描述", "Add description": "添加描述", "Tags": "标签", "Campaign ID": "营销活动 ID", "Copied": "已复制", "Copy": "复制", "Variants": "变体", "Add variant": "添加变体", "Email Composer": "邮件编辑器", "Create new email": "创建新邮件", "How would you like to start?": "你想如何开始？", "Generate a custom email": "生成自定义邮件", "Drag-and-drop editor": "拖放编辑器", "HTML code editor": "HTML 代码编辑器", "Start from scratch": "从头开始", "Templates": "模板", "Choose a template": "选择模板", "Upload file": "上传文件", "Sending info": "发送信息", "From": "发件人", "Subject": "主题", "Preheader": "预标题", "One-click list-unsubscribe": "一键退订列表", "Edit sending info": "编辑发送信息", "Email body": "邮件正文", "Edit message": "编辑消息", "Choose New Template": "选择新模板", "Preview and test": "预览和测试", "Back to campaign": "返回营销活动", "Sending settings": "发送设置", "Preview & Test": "预览与测试", "HTML code": "HTML 代码", "Generate email": "生成邮件", "Email preview": "邮件预览", "Message settings": "消息设置", "Subject line": "主题行", "Personalization": "个性化", "Email sending settings": "邮件发送设置", "Email editor sections": "邮件编辑器区域", "Languages": "语言", "Advanced": "高级", "Style Settings": "样式设置", "Download file": "下载文件", "Done": "完成", "Braze drag-and-drop email editor": "Braze 拖放邮件编辑器", "Content Build": "内容构建", "Link Management": "链接管理", "Drag content here to build your email": "将内容拖到此处以构建邮件", "CONTENT": "内容", "BASIC BLOCKS": "基础组件", "MEDIA": "媒体", "ADVANCED": "高级", "ROWS": "行", "SETTINGS": "设置", "TITLE": "标题", "PARAGRAPH": "段落", "LIST": "列表", "BUTTON": "按钮", "DIVIDER": "分隔线", "SPACER": "空白", "IMAGE": "图片", "VIDEO": "视频", "SOCIAL": "社交", "HTML": "HTML", "MENU": "菜单",
    "Delivery": "投递", "Choose a Type": "选择类型", "Scheduled": "定时", "Action-Based": "基于操作", "API-Triggered": "API 触发", "Enter users at designated times": "在指定时间让用户进入", "Enter user when they perform actions": "用户执行操作时进入", "Enter users via API request": "通过 API 请求让用户进入", "Time-Based Scheduling Options": "基于时间的计划选项", "Action-Based Scheduling Options": "基于操作的计划选项", "API-Triggered Scheduling Options": "API 触发计划选项", "Send as soon as Campaign is launched": "营销活动启动后立即发送", "Send at a designated time": "在指定时间发送", "Choose a time for users to receive this message.": "选择用户接收此消息的时间。", "Intelligent Timing": "智能时间", "Each user will receive the Campaign at the time they are most likely to engage.": "每位用户将在最有可能互动的时间收到营销活动。", "Entry Frequency": "进入频率", "Start date": "开始日期", "Send time": "发送时间", "Enter users into this Campaign in their local time zone": "按用户本地时区让其进入此营销活动", "Next Send Time": "下次发送时间", "Trigger event": "触发事件", "Delay in minutes": "延迟（分钟）", "Enter users via an API request after launching this Campaign.": "启动营销活动后，通过 API 请求让用户进入。", "Delivery Controls": "投递控制", "Manage the number of messages your users will receive.": "管理用户将收到的消息数量。", "Allow users to become re-eligible to receive campaign": "允许用户重新获得接收营销活动的资格", "Re-eligibility after": "重新获得资格的间隔", "Frequency Capping": "频次上限", "You have not created any Frequency Capping rules.": "尚未创建任何频次上限规则。", "Apply quiet hours": "应用静默时段",
    "Targeting Options": "目标选项", "Target users by choosing multiple segments they must fall into. Further refine your audience by adding additional filters.": "选择用户必须属于的多个细分，并通过其他筛选条件进一步缩小受众范围。", "Target Users By Segment": "按细分选择目标用户", "Additional Filters": "其他筛选条件", "Add filter group": "添加筛选组", "Add exclusion group": "添加排除组", "Audience Summary": "受众摘要", "User Lookup": "用户查找", "Check if a user matches the segment, filter, and app criteria": "检查用户是否符合细分、筛选和应用条件", "Lookup User": "查找用户", "Search user ID": "搜索用户 ID", "Send to these users:": "发送给这些用户：", "Subscription group": "订阅组", "Limit send volume": "限制发送量", "Maximum users": "最大用户数", "Limit the rate at which this Campaign will send": "限制此营销活动的发送速率", "Messages per minute": "每分钟消息数", "A/B Testing": "A/B 测试", "Optimize with BrazeAI™": "使用 BrazeAI™ 优化", "There are no suppression lists applied": "未应用任何抑制列表", "Total Population": "总人数", "Exact users": "精确用户数", "Channel breakdown": "渠道明细",
    "Assign Conversion Events": "分配转化事件", "Define up to 4 conversion events to track for this Campaign. The conversion events must be assigned during Campaign creation, and cannot be changed once a Campaign has launched.": "最多定义 4 个转化事件用于跟踪此营销活动。转化事件必须在创建营销活动时分配，启动后无法更改。", "Conversion event type": "转化事件类型", "Apps and websites targeted": "目标应用和网站", "Conversion deadline": "转化截止时间", "Define the maximum time that may pass between a user entering a Campaign and the conversion.": "定义用户进入营销活动到完成转化之间允许经过的最长时间。", "Add Conversion Event": "添加转化事件", "Review Campaign Summary": "审核营销活动摘要", "Complete before launch": "启动前需要完成", "Messages": "消息", "Edit Messages": "编辑消息", "Edit Delivery": "编辑投递", "Target Audience": "目标受众", "Edit Target Audience": "编辑目标受众", "Entry Audience": "进入受众", "Conversion Events": "转化事件", "Edit Conversion Events": "编辑转化事件",
    "Search Users": "搜索用户", "Search users": "搜索用户", "Inspect synthetic user profiles and update their local subscription state.": "查看模拟用户档案并更新本地订阅状态。", "Search by external ID, email, or name": "按外部 ID、邮箱或姓名搜索", "External ID": "外部 ID", "Country": "国家或地区", "Lifecycle": "生命周期", "Reachable": "可触达", "Subscription": "订阅", "Subscribed": "已订阅", "Reachable subscribers": "可触达订阅用户", "No users match this search.": "没有符合搜索条件的用户。", "Select a user to inspect attributes.": "选择一个用户查看属性。", "User profile": "用户档案", "Attribute": "属性", "Yes": "是", "No": "否",
    "Build, validate, save, and simulate a local customer journey.": "构建、校验、保存并模拟本地客户旅程。", "Launch Canvas": "启动画布", "Steps": "步骤", "Inspector": "检查器", "Select a node": "选择节点", "Step name": "步骤名称", "Delay (hours)": "延迟（小时）", "Message": "消息", "Event": "事件", "Equals": "等于", "Copy step": "复制步骤", "Delete step": "删除步骤", "Connect from this step": "从此步骤连接", "Select a destination step to create a connection.": "选择目标步骤以创建连接。", "First outgoing route is Yes; second is No.": "第一条传出路径为“是”，第二条为“否”。", "Undo": "撤销", "Redo": "重做", "Execution": "执行", "No executions yet": "暂无执行记录", "Launch to inspect the local path.": "启动后可查看本地执行路径。", "User path": "用户路径", "entered": "进入", "completed": "完成",
    "Performance": "效果", "Last 7 days": "过去 7 天", "Last 30 days": "过去 30 天", "Last 90 days": "过去 90 天", "Delivery run chart": "投递运行图", "Delivery runs": "投递运行", "Each bar is a completed local Campaign or Canvas execution snapshot.": "每个柱形代表一次已完成的本地营销活动或画布执行快照。", "Metrics are calculated from local execution runs and message events.": "指标根据本地执行记录和消息事件计算。", "Sent": "已发送", "Delivered": "已送达", "of delivered": "占已送达", "messages": "条消息", "users": "位用户",
    "Demo Lab": "演示实验室", "Control the same SQLite data that powers campaign execution, activity, and reports.": "控制用于营销活动执行、活动日志和报表的同一份 SQLite 数据。", "Demo clock": "演示时钟", "The clock is a local simulation; it does not trigger scheduled campaigns.": "该时钟仅用于本地模拟，不会触发计划中的营销活动。", "Launch a Campaign or Canvas to create report data.": "启动营销活动或画布以生成报表数据。", "deliveries awaiting receipt generation": "个投递等待生成回执", "Stop date": "停止日期", "Your getting started checklist": "入门检查清单", "Explore Braze features in the demo workspace, then switch into the live workspace to launch a campaign.": "在演示工作区中探索 Braze 功能，然后切换到实时工作区启动营销活动。", "milestones completed": "个里程碑已完成", "Toggle milestone": "切换里程碑状态", "Get to know the Braze dashboard": "了解 Braze 仪表板", "Explore key features and create your first content.": "探索核心功能并创建第一份内容。", "Send your first live email campaign": "发送首个实时邮件营销活动", "Create a campaign and send a simulated test.": "创建营销活动并发送模拟测试。", "Scale your strategy": "扩展营销策略", "Build a segment and an automated journey.": "创建细分和自动化旅程。", "Begin": "开始",
    "Message Activity Log": "消息活动日志", "Local test, delivery, engagement, suppression and failure events.": "本地测试、投递、互动、抑制和失败事件。", "No message events have been recorded.": "尚未记录消息事件。", "Timestamp": "时间戳", "User": "用户",
    "View only": "仅查看", "Search": "搜索", "Clear search": "清除搜索", "Results": "个结果", "Result": "个结果", "Name": "名称", "Description": "描述", "Source": "来源", "Items": "项目", "Total size": "总大小", "Last updated": "上次更新", "Preview": "预览", "Selections": "精选", "Create recommendation": "创建推荐", "User preview": "用户预览", "Get random user": "获取随机用户", "Generate preview": "生成预览", "Close": "关闭", "Close item details": "关闭项目详情", "View item": "查看项目", "View Item": "查看项目", "No results found": "未找到结果", "Try changing your filters or search terms.": "请尝试更改筛选条件或搜索词。", "Reset filters": "重置筛选", "Showing rows": "显示行", "Rows per page": "每页行数", "Previous page": "上一页", "Next page": "下一页", "of": "共", "Package": "套餐", "Free": "免费版", "of 500MB space used": "已使用（共 500MB）", "Privacy preferences": "隐私偏好", "Status": "状态", "Terms": "条款", "Privacy": "隐私", "Search for catalogs": "搜索目录", "Search for an item by ID": "按 ID 搜索项目", "Search by selection name": "按精选名称搜索", "Filter field": "筛选字段", "Select a field": "选择字段", "Operator": "运算符", "Value": "值", "Apply": "应用", "Clear": "清除", "Feedback is unavailable in this local demo.": "本地演示中暂不提供反馈功能。", "Loading catalog…": "正在加载目录…", "Catalog not found": "未找到目录", "Back to Catalogs": "返回目录", "View selection": "查看精选", "Selections are subsets of a catalog that can be used to personalize messages for each user in your marketing campaigns.": "精选是目录的子集，可用于在营销活动中为每位用户个性化消息。", "Filter settings": "筛选设置", "Add filter": "添加筛选条件", "Sorting type": "排序类型", "Random sort": "随机排序", "Sort field": "排序字段", "Sort": "排序", "Results limit": "结果数量上限", "You can include up to 50 catalog items in a selection.": "一个精选最多可以包含 50 个目录项目。", "Preview how this selection appears for a user before using it in a message.": "在消息中使用前，预览此精选对特定用户的显示结果。", "Random user": "随机用户", "Preview results": "预览结果", "Loading selection…": "正在加载精选…", "Selection not found": "未找到精选", "Configure the settings for Canvases and campaigns connected to this catalog.": "配置与此目录关联的画布和营销活动设置。", "Read more in documentation.": "在文档中了解更多。", "Back in stock": "恢复库存", "Price drop": "降价", "Notification rules": "通知规则", "Notification rules do not replace campaign or Canvas notification settings (for example, quiet hours).": "通知规则不会取代营销活动或画布中的通知设置（例如静默时段）。", "Notify all subscribed users": "通知所有已订阅用户", "Notify a certain number of users per 10 minutes": "每 10 分钟通知指定数量的用户", "Subscriptions": "订阅", "Users who subscribed to catalog notifications. Subscriptions expire when messages are sent, after 90 days, or when users perform the custom event for unsubscribing.": "已订阅目录通知的用户。消息发送后、90 天后或用户触发退订自定义事件时，订阅将失效。", "Active subscriptions": "有效订阅", "Show last 10 subscriptions": "显示最近 10 条订阅", "User ID": "用户 ID", "Item ID": "项目 ID", "Type": "类型",
    "Recommendations are available in your Free plan.": "免费版可使用推荐功能。", "Learn more": "了解更多", "Step": "步骤", "Recommendation details": "推荐详情", "Define your recommendation": "定义推荐", "Track your recommendation": "跟踪推荐", "Give your recommendation a name and description.": "为推荐填写名称和描述。", "Select the catalog and recommendation type that will define your personalized content.": "选择用于定义个性化内容的目录和推荐类型。", "Select a type": "选择类型", "Personalized": "个性化", "Most popular": "最热门", "Recently viewed": "最近浏览", "Catalog": "目录", "Select a catalog": "选择目录", "Selection": "精选", "No selection": "不使用精选", "Choose the behavior that determines the order of recommended catalog items.": "选择用于决定推荐项目排序的行为。", "Property name": "属性名称", "Match this property to the catalog item ID used in your tracking event.": "将此属性与跟踪事件中使用的目录项目 ID 匹配。", "Continue": "继续", "Save recommendation": "保存推荐", "Loading recommendation…": "正在加载推荐…",
    "Subscription Group Management": "订阅组管理", "Create subscription group": "创建订阅组", "Create subscription groups to collect and manage user subscriptions for email, SMS, and WhatsApp.": "创建订阅组，以收集和管理用户对邮件、短信和 WhatsApp 的订阅。", "Learn more about subscription groups": "了解订阅组", "Subscription status is stored per user and per group. Campaign eligibility uses the selected group when one is configured.": "订阅状态按用户和订阅组分别保存。配置订阅组后，营销活动将据此判断发送资格。", "Search subscription groups": "搜索订阅组", "All channels": "所有渠道", "All statuses": "所有状态", "Reset": "重置", "Subscribers": "订阅用户", "Subscriber": "订阅用户", "Archived": "已归档", "Loading subscription groups…": "正在加载订阅组…", "No subscription groups match these filters.": "没有符合筛选条件的订阅组。", "Subscription status": "订阅状态", "Unsubscribed": "已退订", "Last changed": "上次更改", "Activity log": "活动日志", "Reactivate": "重新启用", "Cancel": "取消", "Saving…": "正在保存…", "Creating…": "正在创建…", "Save changes": "保存更改", "Users can subscribe or unsubscribe from this group independently.": "用户可以单独订阅或退订此组。", "Subscription group name": "订阅组名称", "e.g. Product updates": "例如：产品更新", "Describe what users will receive": "说明用户将收到的内容", "Subscribed users": "已订阅用户", "Users with a recorded status": "已有状态记录的用户", "Delivery channel": "投递渠道", "Search by user ID or email": "按用户 ID 或邮箱搜索", "Loading subscribers…": "正在加载订阅用户…", "No subscribers match these filters.": "没有符合筛选条件的订阅用户。", "No description provided.": "未提供描述。", "Subscription group settings": "订阅组设置", "Changing the channel does not alter the existing subscription state for any user.": "更改渠道不会改变任何用户现有的订阅状态。", "Group created": "订阅组已创建", "Last configuration update": "上次配置更新", "Changes to group settings and subscriber status are written to the local SQLite audit log.": "订阅组设置和用户订阅状态的更改会写入本地 SQLite 审计日志。", "Manage": "管理",
    "Email Preference Centers": "邮件偏好中心", "Create preference center": "创建偏好中心", "Build a preference center where users can control their email subscription groups.": "创建偏好中心，让用户管理自己的邮件订阅组。", "Learn more about preference centers": "了解偏好中心", "Subscription groups": "订阅组", "No preference centers have been created.": "尚未创建偏好中心。", "Create email preference center": "创建邮件偏好中心", "Choose the email subscription groups users can manage.": "选择允许用户管理的邮件订阅组。", "Email subscription groups": "邮件订阅组", "Marketing preferences": "营销偏好", "Explain what users can manage": "说明用户可以管理的内容", "Optional": "可选"
  },
  ko: {
    "Search workspace": "워크스페이스 검색", "Quick links": "빠른 링크", "Canvas": "캔버스", "Campaigns": "캠페인", "Segments": "세그먼트", "Getting Started": "시작하기", "Performance Overview": "성과 개요", "Agent Console": "에이전트 콘솔", "Messaging": "메시징", "Audience": "오디언스", "Content": "콘텐츠", "Analytics": "분석", "Partner Integrations": "파트너 통합", "Data Settings": "데이터 설정", "Settings": "설정", "Catalogs": "카탈로그", "View only": "보기 전용", "Search": "검색", "Clear search": "검색 지우기", "Results": "개 결과", "Name": "이름", "Description": "설명", "Source": "소스", "Items": "항목", "Total size": "전체 크기", "Last updated": "마지막 수정", "Preview": "미리보기", "Selections": "선택", "Create recommendation": "추천 만들기", "Language": "언어", "User preview": "사용자 미리보기", "Get random user": "임의 사용자 가져오기", "Generate preview": "미리보기 생성", "Close": "닫기"
  },
  ja: {
    "Search workspace": "ワークスペースを検索", "Quick links": "クイックリンク", "Canvas": "キャンバス", "Campaigns": "キャンペーン", "Segments": "セグメント", "Getting Started": "はじめに", "Performance Overview": "パフォーマンス概要", "Agent Console": "エージェントコンソール", "Messaging": "メッセージング", "Audience": "オーディエンス", "Content": "コンテンツ", "Analytics": "分析", "Partner Integrations": "パートナー連携", "Data Settings": "データ設定", "Settings": "設定", "Catalogs": "カタログ", "View only": "閲覧のみ", "Search": "検索", "Clear search": "検索をクリア", "Results": "件の結果", "Name": "名前", "Description": "説明", "Source": "ソース", "Items": "アイテム", "Total size": "合計サイズ", "Last updated": "最終更新", "Preview": "プレビュー", "Selections": "選択", "Create recommendation": "レコメンデーションを作成", "Language": "言語", "User preview": "ユーザープレビュー", "Get random user": "ランダムユーザーを取得", "Generate preview": "プレビューを生成", "Close": "閉じる"
  }
};

export function normalizeLocale(value: string | null | undefined): Locale { return supportedLocales.includes(value as Locale) ? value as Locale : "en"; }
export function translate(locale: Locale, text: string) { return locale === "en" ? text : dictionaries[locale][text] ?? text; }

export function withLocale(path: string, locale: Locale) {
  const url = new URL(path, "http://localhost");
  url.searchParams.set("locale", locale);
  return `${url.pathname}${url.search}${url.hash}`;
}

export function formatNumber(locale: Locale, value: number) {
  return new Intl.NumberFormat(locale).format(value);
}

export function formatDate(locale: Locale, value: string | number | Date, options: Intl.DateTimeFormatOptions = { dateStyle: "medium" }) {
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? String(value) : new Intl.DateTimeFormat(locale, options).format(date);
}
