"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Archive, ChevronLeft, ExternalLink, MoreHorizontal, Plus, Search, SlidersHorizontal, UserCheck, X } from "lucide-react";
import styles from "./subscription-group-workspace.module.css";
import type { Locale } from "@/lib/i18n";

type Channel = "Email" | "SMS" | "WhatsApp";
type Group = { id: string; name: string; description: string; channel: Channel; status: "Active" | "Archived"; createdAt: string; updatedAt: string; subscriberCount: number };
type Member = { id: string; email: string; firstName: string; country: string; lifecycle: string; reachable: boolean; state: "subscribed" | "unsubscribed"; updatedAt: string };
type Center = { id: string; name: string; description: string; groupIds: string[]; status: "Active" | "Draft"; updatedAt: string };
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(value));

async function responseJson<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, options); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Request failed"); return body; }

export function SubscriptionGroupWorkspace({ locale: _locale, notify }: { locale: Locale; notify: (message: string) => void }) {
  const [groups, setGroups] = useState<Group[]>([]); const [query, setQuery] = useState(""); const [channel, setChannel] = useState("All channels"); const [status, setStatus] = useState("All statuses");
  const [selectedId, setSelectedId] = useState<string | null>(null); const [createOpen, setCreateOpen] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams({ q: query, channel, status }); const result = await responseJson<{ data: Group[] }>(`/api/subscription-groups?${params}`); setGroups(result.data); } catch { notify("Unable to load subscription groups."); } finally { setLoading(false); } }, [channel, notify, query, status]);
  useEffect(() => { const id = window.setTimeout(() => void load(), 150); return () => window.clearTimeout(id); }, [load]);
  const selected = groups.find(group => group.id === selectedId) ?? null;
  if (selected) return <SubscriptionGroupDetail group={selected} back={() => { setSelectedId(null); void load(); }} notify={notify}/>;
  return <section className={styles.page}>
    <header className={styles.heading}><div><h1>Subscription Group Management</h1><p>Create subscription groups to collect and manage user subscriptions for email, SMS, and WhatsApp.</p><a href="https://www.braze.com/docs/user_guide/message_building_by_channel/email/managing_user_subscriptions/" target="_blank">Learn more about subscription groups <ExternalLink size={13}/></a></div><button className="primary" onClick={() => setCreateOpen(true)}><Plus size={16}/> Create subscription group</button></header>
    <div className={styles.notice}><UserCheck size={18}/><span>Subscription status is stored per user and per group. Campaign eligibility uses the selected group when one is configured.</span></div>
    <div className={styles.toolbar}><label className={styles.search}><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search subscription groups"/></label><label><span>Channel</span><select value={channel} onChange={event => setChannel(event.target.value)}><option>All channels</option><option>Email</option><option>SMS</option><option>WhatsApp</option></select></label><label><span>Status</span><select value={status} onChange={event => setStatus(event.target.value)}><option>All statuses</option><option>Active</option><option>Archived</option></select></label><button className="secondary" onClick={() => { setQuery(""); setChannel("All channels"); setStatus("All statuses"); }}><SlidersHorizontal size={15}/> Reset</button></div>
    <div className={styles.results}>{loading ? "Loading subscription groups…" : `${groups.length} subscription group${groups.length === 1 ? "" : "s"}`}</div>
    <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Name</th><th>Channel</th><th>Description</th><th>Subscribers</th><th>Last updated</th><th aria-label="Actions"/></tr></thead><tbody>{groups.length ? groups.map(group => <tr key={group.id}><td><button className={styles.groupLink} onClick={() => setSelectedId(group.id)}>{group.name}</button><span className={group.status === "Active" ? styles.active : styles.archived}>{group.status}</span></td><td><span className={styles.channel}>{group.channel}</span></td><td className={styles.description}>{group.description || "—"}</td><td>{group.subscriberCount.toLocaleString()}</td><td>{formatDate(group.updatedAt)}</td><td><button className="icon-button" aria-label={`Manage ${group.name}`} onClick={() => setSelectedId(group.id)}><MoreHorizontal size={18}/></button></td></tr>) : <tr><td colSpan={6}><div className={styles.empty}>No subscription groups match these filters.</div></td></tr>}</tbody></table></div>
    {createOpen && <CreateGroupModal close={() => setCreateOpen(false)} created={group => { setCreateOpen(false); setSelectedId(group.id); notify("Subscription group created."); }}/>} 
  </section>;
}

function CreateGroupModal({ close, created }: { close: () => void; created: (group: Group) => void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [channel, setChannel] = useState<Channel>("Email"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async () => { setSaving(true); setError(""); try { created(await responseJson<Group>("/api/subscription-groups", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, channel }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create subscription group"); setSaving(false); } };
  return <div className="modal-backdrop"><section className={styles.modal} aria-modal="true" role="dialog"><header><div><h2>Create subscription group</h2><p>Users can subscribe or unsubscribe from this group independently.</p></div><button className="icon-button" onClick={close}><X size={18}/></button></header><label>Subscription group name<input autoFocus value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Product updates"/></label><label>Channel<select value={channel} onChange={event => setChannel(event.target.value as Channel)}><option>Email</option><option>SMS</option><option>WhatsApp</option></select></label><label>Description<textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Describe what users will receive"/></label>{error && <p className="form-error">{error}</p>}<footer><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!name.trim() || saving} onClick={() => void submit()}>{saving ? "Creating…" : "Create subscription group"}</button></footer></section></div>;
}

function SubscriptionGroupDetail({ group: initialGroup, back, notify }: { group: Group; back: () => void; notify: (message: string) => void }) {
  const [group, setGroup] = useState(initialGroup); const [tab, setTab] = useState<"subscribers" | "settings" | "activity">("subscribers"); const [members, setMembers] = useState<Member[]>([]); const [total, setTotal] = useState(0); const [query, setQuery] = useState(""); const [state, setState] = useState("All statuses"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const params = new URLSearchParams({ q: query, state, limit: "20" }); const result = await responseJson<{ data: Member[]; total: number }>(`/api/subscription-groups/${group.id}/members?${params}`); setMembers(result.data); setTotal(result.total); } catch { notify("Unable to load subscribers."); } finally { setLoading(false); } }, [group.id, notify, query, state]);
  useEffect(() => { if (tab !== "subscribers") return; const id = window.setTimeout(() => void load(), 120); return () => window.clearTimeout(id); }, [load, tab]);
  const changeMember = async (member: Member) => { try { const next = member.state === "subscribed" ? "unsubscribed" : "subscribed"; await responseJson(`/api/subscription-groups/${group.id}/members`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: member.id, state: next }) }); notify(`${member.email} is now ${next}.`); void load(); const refreshed = await responseJson<Group>(`/api/subscription-groups/${group.id}`); setGroup(refreshed); } catch { notify("Unable to update subscription status."); } };
  const archive = async () => { setSaving(true); try { const updated = await responseJson<Group>(`/api/subscription-groups/${group.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: group.status === "Active" ? "Archived" : "Active" }) }); setGroup(updated); notify(updated.status === "Archived" ? "Subscription group archived." : "Subscription group reactivated."); } catch { notify("Unable to change subscription group status."); } finally { setSaving(false); } };
  return <section className={styles.page}><button className={styles.back} onClick={back}><ChevronLeft size={17}/> Subscription Group Management</button><header className={styles.detailHeading}><div><div className={styles.eyebrow}>{group.channel} subscription group</div><h1>{group.name}</h1><p>{group.description || "No description provided."}</p></div><button className="secondary" disabled={saving} onClick={() => void archive()}><Archive size={15}/>{group.status === "Active" ? "Archive" : "Reactivate"}</button></header><nav className={styles.tabs}>{(["subscribers", "settings", "activity"] as const).map(value => <button key={value} className={tab === value ? styles.selectedTab : ""} onClick={() => setTab(value)}>{value === "subscribers" ? "Subscribers" : value === "settings" ? "Settings" : "Activity log"}</button>)}</nav>{tab === "subscribers" ? <><div className={styles.summary}><div><b>{group.subscriberCount.toLocaleString()}</b><span>Subscribed users</span></div><div><b>{total.toLocaleString()}</b><span>Users with a recorded status</span></div><div><b>{group.channel}</b><span>Delivery channel</span></div></div><div className={styles.toolbar}><label className={styles.search}><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by user ID or email"/></label><label><span>Subscription status</span><select value={state} onChange={event => setState(event.target.value)}><option>All statuses</option><option value="subscribed">Subscribed</option><option value="unsubscribed">Unsubscribed</option></select></label></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>User</th><th>Country</th><th>Lifecycle</th><th>Reachable</th><th>Subscription status</th><th>Last changed</th></tr></thead><tbody>{members.length ? members.map(member => <tr key={member.id}><td><b>{member.id}</b><small>{member.email}</small></td><td>{member.country}</td><td>{member.lifecycle}</td><td>{member.reachable ? "Yes" : "No"}</td><td><button className={member.state === "subscribed" ? styles.subscribed : styles.unsubscribed} onClick={() => void changeMember(member)}>{member.state === "subscribed" ? "Subscribed" : "Unsubscribed"}</button></td><td>{formatDate(member.updatedAt)}</td></tr>) : <tr><td colSpan={6}><div className={styles.empty}>{loading ? "Loading subscribers…" : "No subscribers match these filters."}</div></td></tr>}</tbody></table></div></> : tab === "settings" ? <GroupSettings group={group} saved={next => { setGroup(next); notify("Subscription group settings saved."); }}/> : <Activity group={group}/>}</section>;
}

function GroupSettings({ group, saved }: { group: Group; saved: (group: Group) => void }) { const [name, setName] = useState(group.name); const [description, setDescription] = useState(group.description); const [channel, setChannel] = useState<Channel>(group.channel); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const submit = async () => { setSaving(true); setError(""); try { saved(await responseJson<Group>(`/api/subscription-groups/${group.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, channel }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save settings"); } finally { setSaving(false); } }; return <section className={styles.settings}><h2>Subscription group settings</h2><p>Changing the channel does not alter the existing subscription state for any user.</p><label>Name<input value={name} onChange={event => setName(event.target.value)}/></label><label>Channel<select value={channel} onChange={event => setChannel(event.target.value as Channel)}><option>Email</option><option>SMS</option><option>WhatsApp</option></select></label><label>Description<textarea value={description} onChange={event => setDescription(event.target.value)}/></label>{error && <p className="form-error">{error}</p>}<button className="primary" disabled={!name.trim() || saving} onClick={() => void submit()}>{saving ? "Saving…" : "Save changes"}</button></section>; }
function Activity({ group }: { group: Group }) { return <section className={styles.activity}><h2>Activity log</h2><p>Changes to group settings and subscriber status are written to the local SQLite audit log.</p><div><b>Group created</b><span>{formatDate(group.createdAt)}</span></div><div><b>Last configuration update</b><span>{formatDate(group.updatedAt)}</span></div></section>; }

export function PreferenceCenterWorkspace({ locale: _locale, notify }: { locale: Locale; notify: (message: string) => void }) {
  const [centers, setCenters] = useState<Center[]>([]); const [groups, setGroups] = useState<Group[]>([]); const [open, setOpen] = useState(false);
  const load = useCallback(async () => { try { const [centerResponse, groupResponse] = await Promise.all([responseJson<{ data: Center[] }>("/api/preference-centers"), responseJson<{ data: Group[] }>("/api/subscription-groups?status=Active")]); setCenters(centerResponse.data); setGroups(groupResponse.data); } catch { notify("Unable to load email preference centers."); } }, [notify]);
  useEffect(() => { void load(); }, [load]);
  return <section className={styles.page}><header className={styles.heading}><div><h1>Email Preference Centers</h1><p>Build a preference center where users can control their email subscription groups.</p><a href="https://www.braze.com/docs/user_guide/message_building_by_channel/email/preference_center/" target="_blank">Learn more about preference centers <ExternalLink size={13}/></a></div><button className="primary" onClick={() => setOpen(true)}><Plus size={16}/> Create preference center</button></header><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Name</th><th>Subscription groups</th><th>Status</th><th>Last updated</th></tr></thead><tbody>{centers.length ? centers.map(center => <tr key={center.id}><td><b>{center.name}</b><small>{center.description}</small></td><td>{center.groupIds.map(id => groups.find(group => group.id === id)?.name ?? id).join(", ") || "—"}</td><td><span className={center.status === "Active" ? styles.active : styles.archived}>{center.status}</span></td><td>{formatDate(center.updatedAt)}</td></tr>) : <tr><td colSpan={4}><div className={styles.empty}>No preference centers have been created.</div></td></tr>}</tbody></table></div>{open && <CreatePreferenceCenter groups={groups} close={() => setOpen(false)} created={() => { setOpen(false); void load(); notify("Preference center created."); }}/>}</section>;
}

function CreatePreferenceCenter({ groups, close, created }: { groups: Group[]; close: () => void; created: () => void }) { const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [ids, setIds] = useState<string[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const toggle = (id: string) => setIds(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); const submit = async () => { setSaving(true); setError(""); try { await responseJson("/api/preference-centers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, groupIds: ids, status: "Active" }) }); created(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create preference center"); setSaving(false); } }; return <div className="modal-backdrop"><section className={styles.modal}><header><div><h2>Create email preference center</h2><p>Choose the email subscription groups users can manage.</p></div><button className="icon-button" onClick={close}><X size={18}/></button></header><label>Name<input autoFocus value={name} onChange={event => setName(event.target.value)} placeholder="Marketing preferences"/></label><label>Description<textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Explain what users can manage"/></label><fieldset className={styles.groupChecklist}><legend>Email subscription groups</legend>{groups.filter(group => group.channel === "Email").map(group => <label key={group.id}><input type="checkbox" checked={ids.includes(group.id)} onChange={() => toggle(group.id)}/><span><b>{group.name}</b><small>{group.description}</small></span></label>)}</fieldset>{error && <p className="form-error">{error}</p>}<footer><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!name.trim() || saving} onClick={() => void submit()}>{saving ? "Creating…" : "Create preference center"}</button></footer></section></div>; }
